---
- hosts: "{{ hadoop_node }}"
  sudo: yes
  remote_user: vagrant
  tasks:
    - name: Install java
      yum: name={{ item }} state=installed
      with_items:
        - java-1.8.0-openjdk.x86_64
        - java-1.8.0-openjdk-devel
